name: pres7t
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-149.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: 4.3.8
  flutter_spinkit: 5.1.0
  filling_slider: 0.0.3
  flutter_svg: 1.0.3
  flutter_screenutil: 5.1.1
  bubble_bottom_bar: 2.0.0
  google_fonts: 2.2.0
  modal_bottom_sheet: 2.0.0
  uni_links: 0.5.1
  flutter_slidable: 1.2.0
  carousel_slider: 4.0.0
  dio: 4.0.4
  liquid_pull_to_refresh: 3.0.1
  flutter_easyrefresh: 2.2.1
  flutter_map: 0.14.0
  cached_network_image: 3.2.0
  titled_navigation_bar: 4.1.0
  curved_navigation_bar: 1.0.3
  custom_navigation_bar: 0.8.2
  animate_do: 2.1.0
  adaptive_theme: 3.0.0
  awesome_dialog: 2.2.1
  # google_maps_flutter: 2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
