name: eventouch
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.3
  flutter_icons:
  get: 4.3.8
  flutter_spinkit: 5.1.0
  filling_slider: 0.0.3
  flutter_svg: 1.0.3
  flutter_screenutil: 5.1.1
  bubble_bottom_bar: 2.0.0
  google_fonts: 2.2.0
  modal_bottom_sheet: 2.0.0
  uni_links: 0.5.1
  flutter_slidable: 1.2.0
  carousel_slider: 4.0.0
  dio: 4.0.4
  awesome_dialog: 2.1.2
  liquid_pull_to_refresh: 3.0.1
  flutter_easyrefresh: 2.2.1
  flutter_map: 0.14.0
  latlong: 0.6.1
  titled_navigation_bar: 4.1.0
  curved_navigation_bar: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
