name: pres7t
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-149.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  get: 4.3.8
  flutter_spinkit: 5.1.0
  flutter_screenutil: 5.1.1
  google_fonts: 2.2.0
  uni_links: 0.5.1
  carousel_slider: 4.0.0
  dio: 4.0.4
  liquid_pull_to_refresh: 3.0.1
  flutter_map: 0.14.0
  cached_network_image: 3.2.0
  custom_navigation_bar: 0.8.2
  animate_do: 2.1.0
  adaptive_theme: 3.0.0
  get_storage: 2.0.3
  flutter_easyloading: 3.0.5
  geolocator: 8.2.1
  app_settings: 4.1.8
  date_time_picker: 2.1.0
  flutter_secure_storage: 5.0.2
  shared_preferences: 2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
